# Generated by Django 5.1.7 on 2025-03-16 15:48

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0007_flat_owner_pure_phone_alter_complaint_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flat",
            name="owner_pure_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Формат: +7XXXXXXXXXX",
                max_length=128,
                null=True,
                region="RU",
                verbose_name="Нормализированный номер владельца",
            ),
        ),
    ]
