# Generated by Django 5.1.7 on 2025-03-16 16:16

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0009_normalize_phones"),
    ]

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=200, verbose_name="ФИО владельца"),
                ),
                (
                    "phonenumber",
                    models.CharField(max_length=20, verbose_name="Номер владельца"),
                ),
                (
                    "pure_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        help_text="Формат: +7XXXXXXXXXX",
                        max_length=128,
                        null=True,
                        region="RU",
                        verbose_name="Нормализованный номер",
                    ),
                ),
                (
                    "flats",
                    models.ManyToManyField(
                        blank=True,
                        related_name="owners",
                        to="property.flat",
                        verbose_name="Квартиры в собственности",
                    ),
                ),
            ],
        ),
    ]
