# Generated by Django 5.1.7 on 2025-03-16 16:21

from django.db import migrations


def migrate_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all().iterator():
        owner, created = Owner.objects.get_or_create(
            full_name=flat.owner,
            phonenumber=flat.owners_phonenumber,
            pure_phone=flat.owner_pure_phone
        )
        owner.flats.add(flat)

class Migration(migrations.Migration):
    dependencies = [
        ("property", "0010_owner"),
    ]

    operations = [
        migrations.RunPython(migrate_owners),
    ]
