# Generated by Django 5.1.7 on 2025-03-17 14:16

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0011_migrate_owners"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flat",
            old_name="owner",
            new_name="owner_deprecated",
        ),
        migrations.RemoveField(
            model_name="flat",
            name="owner_pure_phone",
        ),
        migrations.RemoveField(
            model_name="flat",
            name="owners_phonenumber",
        ),
        migrations.AlterField(
            model_name="owner",
            name="full_name",
            field=models.CharField(
                db_index=True, max_length=200, verbose_name="ФИО владельца"
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="phonenumber",
            field=models.CharField(
                db_index=True, max_length=20, verbose_name="Номер владельца"
            ),
        ),
        migrations.AlterField(
            model_name="owner",
            name="pure_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                db_index=True,
                help_text="Формат: +7XXXXXXXXXX",
                max_length=128,
                null=True,
                region="RU",
                verbose_name="Нормализованный номер",
            ),
        ),
    ]
